name: Erlang CI

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ["25.3"]
        rebar3: ["3.24.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 dialyzer
      - run: rebar3 eunit
      - run: rebar3 ct
